In [ ]:

from pathlib import Path

parquet_file_path = Path('filename.parquet')

print(parquet_file_path.suffix)

In [3]:
import tools.price_histories_helper as phh
price_histories_path = Path('../data/price_histories_yahoo.parquet')
price_histories_df = phh.load_price_histories(price_histories_path)
display(price_histories_df.describe())

Attributes        Close                                                      \
Symbols               A          AAL          AAP         AAPL         ABBV
count       1259.000000  1259.000000  1259.000000  1259.000000  1259.000000
mean         105.517593    22.481541   158.124623   103.286648    98.448094
std           33.668999     9.106484    30.370953    46.086408    31.885207
min           58.910000     9.040000    70.080000    34.260000    53.030000
25%           73.470000    14.420000   140.690000    52.600000    73.220000
50%          103.730000    19.760000   150.310000   115.550000    86.370000
75%          134.065000    30.180000   179.575000   145.555000   128.955000
max          177.360000    45.580000   230.370000   180.680000   167.010000

Attributes                                                                   \
Symbols             ABC          ABT         ACGL          ACN         ADBE
count       1259.000000  1259.000000  1259.000000  1259.000000  1259.000000
mean         107.288618    93.870961    39.355973   232.287466   386.735353
std           29.548471    21.131590    10.443742    66.584836   120.055448
min           66.140000    53.290000    22.240000   125.600000   205.160000
25%           81.765000    76.245000    30.850000   171.310000   278.380000
50%           97.420000    98.560000    38.990000   228.690000   366.740000
75%          132.155000   111.680000    44.515000   282.980000   472.265000
max          173.460000   137.810000    72.250000   406.560000   688.370000

Attributes  ...        Volume                                            \
Symbols     ...          WYNN           XEL           XOM          XRAY
count       ...  1.259000e+03  1.259000e+03  1.259000e+03  1.259000e+03
mean        ...  3.237043e+06  3.173801e+06  2.076510e+07  1.964359e+06
std         ...  2.190703e+06  1.421133e+06  1.097304e+07  1.325411e+06
min         ...  4.721000e+05  0.000000e+00  3.979400e+06  2.176000e+05
25%         ...  1.934000e+06  2.292700e+06  1.301035e+07  1.206550e+06
50%         ...  2.653900e+06  2.844000e+06  1.820890e+07  1.662600e+06
75%         ...  3.847600e+06  3.638900e+06  2.599365e+07  2.382950e+06
max         ...  2.608880e+07  1.599120e+07  8.443940e+07  2.326880e+07

Attributes                                                          \
Symbols              XYL           YUM           ZBH          ZBRA
count       1.259000e+03  1.259000e+03  1.259000e+03  1.259000e+03
mean        1.060736e+06  1.831395e+06  1.329335e+06  4.182985e+05
std         6.096117e+05  9.011658e+05  6.722607e+05  4.029536e+05
min         1.846000e+05  3.404000e+05  2.523500e+05  8.100000e+04
25%         7.135500e+05  1.282800e+06  8.935155e+05  2.614000e+05
50%         9.171000e+05  1.635100e+06  1.174097e+06  3.502000e+05
75%         1.259650e+06  2.124350e+06  1.562304e+06  4.901000e+05
max         1.167510e+07  1.461010e+07  7.107800e+06  1.157870e+07

Attributes
Symbols             ZION           ZTS
count       1.259000e+03  1.259000e+03
mean        2.086055e+06  2.062539e+06
std         1.613554e+06  8.751284e+05
min         3.094000e+05  4.174000e+05
25%         1.252450e+06  1.489000e+06
50%         1.668700e+06  1.879000e+06
75%         2.375150e+06  2.433800e+06
max         2.612990e+07  9.403200e+06

[8 rows x 2505 columns]

In [4]:
price_histories_df.sample(10)

Attributes   Close                                                        \
Symbols          A    AAL     AAP    AAPL    ABBV     ABC     ABT   ACGL
Date
2019-03-26   78.25  29.81  156.56   45.20   66.10   71.89   73.74  31.96
2020-02-13   83.64  30.09  125.44   79.63   82.55   90.45   84.11  47.83
2020-12-01  113.62  14.27  143.02  121.08   93.79   99.10  104.08  33.02
2019-06-25   70.50  30.94  143.80   47.50   54.48   79.55   78.95  35.91
2020-07-24   93.21  11.39  137.80   91.06   86.37   99.79   94.61  30.85
2019-08-05   64.17  28.23  133.25   46.96   54.92   83.73   78.23  37.76
2020-03-10   71.35  17.00  125.93   69.94   75.78   82.37   76.71  37.83
2020-11-24  112.95  14.82  140.42  113.63   93.72   99.98  103.24  34.55
2021-05-18  127.21  23.56  188.02  123.57  108.20  114.30  113.09  40.17
2019-05-13   71.79  31.81  144.55   45.11   63.75   71.07   70.76  33.32

Attributes                  ...   Volume                                       \
Symbols        ACN    ADBE  ...     WYNN      XEL       XOM     XRAY      XYL
Date                        ...
2019-03-26  156.86  265.59  ...   944000  2066300   9472800   829900   483800
2020-02-13  202.87  374.84  ...  3013600  2430700  16949400   860300  2098600
2020-12-01  243.88  479.15  ...  2816000  3937000  32472900  1190000  1026100
2019-06-25  175.17  287.97  ...  1922700  3847700   9740000  1357000   844000
2020-07-24  213.24  430.31  ...  3446900  1503000  16415300  1238500   998600
2019-08-05  175.79  280.36  ...  3578000  4839800  19080900  3117600   872600
2020-03-10  166.73  332.38  ...  5037300  8897400  60445900  2533800  2743100
2020-11-24  241.68  462.70  ...  4229700  4927500  46979300   981800  1151100
2021-05-18  275.38  480.62  ...  2015100  2168200  25170800  1987800   589900
2019-05-13  162.02  267.70  ...  4116800  3695800  12176100  1637600  1040500

Attributes
Symbols         YUM      ZBH     ZBRA     ZION      ZTS
Date
2019-03-26  1361100   832961   476500  4080400  1795400
2020-02-13  1135100   765496  1783600  1293400  3384500
2020-12-01  1726200   963256   403700  2455800  1964400
2019-06-25  1540700   910829   546100  1412500  1669200
2020-07-24  1022600   767659   423100  1520100  1214800
2019-08-05  1897600  1982029   623200  3966700  3488100
2020-03-10  3464100  2729397   909900  4999100  3265500
2020-11-24  1439900  1136708   566700  2578600  2425500
2021-05-18  1426300   888581   198300  1647800  1149500
2019-05-13  1286000  1114254  1199800  2551800  1754400

[10 rows x 2505 columns]