In [6]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [5]:
def get_snp500():
    # Create a Response object
    r = requests.get('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')

    # Get HTML data
    html_data = r.text

    # Create a BeautifulSoup Object
    paget_snp500ge_content = BeautifulSoup(html_data, 'html.parser')

    # Find financipaget_snp500ge_contental table
    #constituents
    wikitable = paget_snp500ge_content.find('table', {'id': 'constituents'})

    # Find all column titles
    wikicolumns = wikitable.findAll('tr')[0].findAll('th')

    # Loop through column titles and store into Python array
    df_columns = []
    for column in wikicolumns:
        # remove <br/> inside <th> text, such as `<th>Total<br/>production</th>`
        text = column.get_text(strip=True, separator=" ")
        # append the text into df_columns
        df_columns.append(text)

    # Loop through the data rows and store into Python array
    df_data = []
    for row in wikitable.tbody.findAll('tr')[1:]:
        row_data = []
        for td in row.findAll('td'):
            text = td.get_text(strip=True, separator=" ")
            row_data.append(text)
        df_data.append(np.array(row_data))    

    # Print financial data in DataFrame format and set `Year` as index
    dataframe = pd.DataFrame(data=df_data, columns=df_columns)
    dataframe.set_index(['Symbol'], inplace=True)
    return dataframe

get_snp500()

,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
Symbol,,,,,,,,
MMM,3M,reports,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1976-08-09,0000066740,1902
ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago , Illinois",1964-03-31,0000001800,1888
ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago , Illinois",2012-12-31,0001551152,2013 (1888)
ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,0000815094,1981
ACN,Accenture,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,0001467373,1989
...,...,...,...,...,...,...,...,...
YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,0001041061,1997
ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,0000877212,1969
ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,0001136869,1927
ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City , Utah",2001-06-22,0000109380,1873
ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,0001555280,1952

In [13]:
def get_dow():
    # Create a Response object
    r = requests.get('https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average')

    # Get HTML data
    html_data = r.text

    # Create a BeautifulSoup Object
    paget_snp500ge_content = BeautifulSoup(html_data, 'html.parser')

    # Find financipaget_snp500ge_contental table
    #constituents
    wikitable = paget_snp500ge_content.find('table', {'id': 'constituents'})

    # Find all column titles
    wikicolumns = wikitable.findAll('tr')[0].findAll('th')

    # Loop through column titles and store into Python array
    df_columns = []
    for column in wikicolumns:
        # remove <br/> inside <th> text, such as `<th>Total<br/>production</th>`
        text = column.get_text(strip=True, separator=" ")
        # append the text into df_columns
        df_columns.append(text)

    # Loop through the data rows and store into Python array
    df_data = []
    for row in wikitable.tbody.findAll('tr')[1:]:
        row_data = []
        for td in row.findAll(['td', 'th']):
            text = td.get_text(strip=True, separator=" ")
            row_data.append(text)
        df_data.append(np.array(row_data))    

    # Print financial data in DataFrame format and set `Year` as index
    dataframe = pd.DataFrame(data=df_data, columns=df_columns)
    dataframe.set_index(['Symbol'], inplace=True)
    return dataframe

get_dow()

,Company,Exchange,Industry,Date added,Notes,Index weighting
Symbol,,,,,,
MMM,3M,NYSE,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,3.73%
AXP,American Express,NYSE,Financial services,1982-08-30,,3.20%
AMGN,Amgen,NASDAQ,Pharmaceutical industry,2020-08-31,,4.52%
AAPL,Apple Inc.,NASDAQ,Information technology,2015-03-19,,2.75%
BA,Boeing,NYSE,Aerospace and defense,1987-03-12,,4.26%
CAT,Caterpillar Inc.,NYSE,Construction and Mining,1991-05-06,,3.88%
CVX,Chevron Corporation,NYSE,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,1.92%
CSCO,Cisco Systems,NASDAQ,Information technology,2009-06-08,,1.05%
KO,The Coca-Cola Company,NYSE,Food industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.07%
DOW,Dow Inc.,NYSE,Chemical industry,2019-04-02,,1.16%
GS,Goldman Sachs,NYSE,Financial services,2013-09-20,,7.15%
HD,The Home Depot,NYSE,Retailing,1999-11-01,,6.18%
HON,Honeywell,NASDAQ,Conglomerate,2020-08-31,,4.39%
IBM,IBM,NYSE,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,2.67%
INTC,Intel,NASDAQ,Information technology,1999-11-01,,1.01%
JNJ,Johnson & Johnson,NYSE,Pharmaceutical industry,1997-03-17,,3.26%
JPM,JPMorgan Chase,NYSE,Financial services,1991-05-06,,2.87%
MCD,McDonald's,NYSE,Food industry,1985-10-30,,4.54%
MRK,Merck & Co.,NYSE,Pharmaceutical industry,1979-06-29,,1.44%
MSFT,Microsoft,NASDAQ,Information technology,1999-11-01,,5.38%
NKE,"Nike, Inc.",NYSE,Apparel,2013-09-20,,3.19%
PG,Procter & Gamble,NYSE,Fast-moving consumer goods,1932-05-26,,2.68%
CRM,Salesforce,NYSE,Information technology,2020-08-31,,4.55%
TRV,The Travelers Companies,NYSE,Financial services,2009-06-08,,2.81%
UNH,UnitedHealth Group,NYSE,Managed health care,2012-09-24,,7.86%
VZ,Verizon Communications,NYSE,Telecommunication,2004-04-08,,1.06%
V,Visa Inc.,NYSE,Financial services,2013-09-20,,4.53%
WBA,Walgreens Boots Alliance,NASDAQ,Retailing,2018-06-26,,0.88%
WMT,Walmart,NYSE,Retailing,1997-03-17,,2.69%
DIS,The Walt Disney Company,NYSE,Broadcasting and entertainment,1991-05-06,,3.32%

In [15]:
def get_wiki_table_stocks(wiki_url, table_id):
    # Create a Response object
    r = requests.get(wiki_url)

    # Get HTML data
    html_data = r.text

    # Create a BeautifulSoup Object
    paget_snp500ge_content = BeautifulSoup(html_data, 'html.parser')

    # Find financipaget_snp500ge_contental table
    #constituents
    wikitable = paget_snp500ge_content.find('table', {'id': table_id})

    # Find all column titles
    wikicolumns = wikitable.findAll('tr')[0].findAll('th')

    # Loop through column titles and store into Python array
    df_columns = []
    for column in wikicolumns:
        # remove <br/> inside <th> text, such as `<th>Total<br/>production</th>`
        text = column.get_text(strip=True, separator=" ")
        # append the text into df_columns
        df_columns.append(text)

    # Loop through the data rows and store into Python array
    df_data = []
    for row in wikitable.tbody.findAll('tr')[1:]:
        row_data = []
        for td in row.findAll(['td', 'th']):
            text = td.get_text(strip=True, separator=" ")
            row_data.append(text)
        df_data.append(np.array(row_data))    

    # Print financial data in DataFrame format and set `Year` as index
    dataframe = pd.DataFrame(data=df_data, columns=df_columns)
    dataframe.set_index(['Symbol'], inplace=True)
    return dataframe

display(get_wiki_table_stocks('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies', 'constituents'))
display(get_wiki_table_stocks('https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average', 'constituents'))

,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
Symbol,,,,,,,,
MMM,3M,reports,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1976-08-09,0000066740,1902
ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago , Illinois",1964-03-31,0000001800,1888
ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago , Illinois",2012-12-31,0001551152,2013 (1888)
ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,0000815094,1981
ACN,Accenture,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,0001467373,1989
...,...,...,...,...,...,...,...,...
YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,0001041061,1997
ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,0000877212,1969
ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,0001136869,1927
ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City , Utah",2001-06-22,0000109380,1873
ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,0001555280,1952

,Company,Exchange,Industry,Date added,Notes,Index weighting
Symbol,,,,,,
MMM,3M,NYSE,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,3.73%
AXP,American Express,NYSE,Financial services,1982-08-30,,3.20%
AMGN,Amgen,NASDAQ,Pharmaceutical industry,2020-08-31,,4.52%
AAPL,Apple Inc.,NASDAQ,Information technology,2015-03-19,,2.75%
BA,Boeing,NYSE,Aerospace and defense,1987-03-12,,4.26%
CAT,Caterpillar Inc.,NYSE,Construction and Mining,1991-05-06,,3.88%
CVX,Chevron Corporation,NYSE,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,1.92%
CSCO,Cisco Systems,NASDAQ,Information technology,2009-06-08,,1.05%
KO,The Coca-Cola Company,NYSE,Food industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.07%
DOW,Dow Inc.,NYSE,Chemical industry,2019-04-02,,1.16%
GS,Goldman Sachs,NYSE,Financial services,2013-09-20,,7.15%
HD,The Home Depot,NYSE,Retailing,1999-11-01,,6.18%
HON,Honeywell,NASDAQ,Conglomerate,2020-08-31,,4.39%
IBM,IBM,NYSE,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,2.67%
INTC,Intel,NASDAQ,Information technology,1999-11-01,,1.01%
JNJ,Johnson & Johnson,NYSE,Pharmaceutical industry,1997-03-17,,3.26%
JPM,JPMorgan Chase,NYSE,Financial services,1991-05-06,,2.87%
MCD,McDonald's,NYSE,Food industry,1985-10-30,,4.54%
MRK,Merck & Co.,NYSE,Pharmaceutical industry,1979-06-29,,1.44%
MSFT,Microsoft,NASDAQ,Information technology,1999-11-01,,5.38%
NKE,"Nike, Inc.",NYSE,Apparel,2013-09-20,,3.19%
PG,Procter & Gamble,NYSE,Fast-moving consumer goods,1932-05-26,,2.68%
CRM,Salesforce,NYSE,Information technology,2020-08-31,,4.55%
TRV,The Travelers Companies,NYSE,Financial services,2009-06-08,,2.81%
UNH,UnitedHealth Group,NYSE,Managed health care,2012-09-24,,7.86%
VZ,Verizon Communications,NYSE,Telecommunication,2004-04-08,,1.06%
V,Visa Inc.,NYSE,Financial services,2013-09-20,,4.53%
WBA,Walgreens Boots Alliance,NASDAQ,Retailing,2018-06-26,,0.88%
WMT,Walmart,NYSE,Retailing,1997-03-17,,2.69%
DIS,The Walt Disney Company,NYSE,Broadcasting and entertainment,1991-05-06,,3.32%

In [1]:
from platform import python_version
import time
from datetime import datetime
import os
import pandas as pd
import numpy as np
import math
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
import pickle

%matplotlib inline
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (20, 8)

# Set the import path for the tools directiory
import sys
# insert at position 1 in the path, as 0 is the path of this file.
sys.path.insert(1, '../tools')
import importlib
import ameritrade_functions as amc
importlib.reload(amc)
import trading_factors as alpha_factors
importlib.reload(alpha_factors)
import utils
importlib.reload(utils)
import nonoverlapping_estimator as ai_estimator
importlib.reload(ai_estimator)

print(f'Python version: {python_version()}')
print(f'Pandas version: {pd.__version__}')

Sci-Kit version: 0.24.1
Sci-Kit version: 0.24.1
Python version: 3.8.10
Pandas version: 0.25.3

# Factor ranking by sector

In [4]:
price_histories_file_name = '../portfolio-ind/data/price_histories.csv'
price_histories = utils.read_price_histories(price_histories_file_name)
print(f'Date range for price histories: {price_histories.date.min().date()} to {price_histories.date.max().date()}')
close = utils.get_close_values(price_histories)
print(f'You have {len(close.columns)} stocks')

Date range for price histories: 2016-11-01 to 2021-10-29
You have 437 stocks

In [52]:
close

ticker,A,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,ADM,...,WY,WYNN,XEL,XOM,XRAY,XYL,YUM,ZBRA,ZION,ZTS
date,,,,,,,,,,,,,,,,,,,,,
2016-11-01 00:00:00+00:00,43.49,139.79,27.8725,56.45,69.79,39.05,116.14,106.87,63.60,46.75,...,28.86,98.23,40.86,83.65,58.40,47.19,60.69,66.58,32.24,47.25
2016-11-02 00:00:00+00:00,43.26,138.14,27.8975,56.79,75.96,38.70,118.61,105.89,63.66,47.26,...,28.30,96.52,40.46,83.45,59.74,46.96,59.70,65.45,30.96,50.11
2016-11-03 00:00:00+00:00,43.66,138.85,27.4575,55.89,72.32,38.38,116.95,107.17,63.85,47.43,...,28.14,87.53,40.62,83.66,59.55,47.24,60.15,64.08,31.17,48.95
2016-11-04 00:00:00+00:00,44.32,136.19,27.2100,56.04,70.47,39.09,117.23,106.20,63.43,46.92,...,28.15,88.04,40.36,83.57,60.60,47.40,59.81,62.97,31.39,49.94
2016-11-07 00:00:00+00:00,45.71,137.54,27.6025,58.91,71.93,39.86,119.97,108.66,64.36,47.05,...,28.79,87.86,41.15,85.45,61.12,48.56,62.01,64.69,32.25,49.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-25 00:00:00+00:00,158.34,230.13,148.6400,108.50,122.60,126.58,356.44,646.97,180.52,66.63,...,37.73,90.42,64.66,64.35,57.27,129.05,125.94,532.46,66.12,211.52
2021-10-26 00:00:00+00:00,158.19,232.56,149.3200,109.49,122.96,128.13,356.34,642.50,179.88,65.36,...,36.76,92.16,64.48,65.84,56.89,127.80,126.18,525.41,65.29,210.52
2021-10-27 00:00:00+00:00,155.26,230.35,148.8500,108.40,119.55,127.71,354.05,640.08,170.46,64.53,...,35.71,91.79,63.39,64.13,56.47,128.00,125.79,517.84,62.88,209.58
2021-10-28 00:00:00+00:00,155.76,225.00,152.5700,109.67,120.70,127.71,356.32,639.28,172.46,64.84,...,36.40,90.78,64.33,64.31,57.27,131.21,125.88,532.06,62.87,212.67
2021-10-29 00:00:00+00:00,157.49,225.52,149.8000,114.67,122.02,128.89,358.79,650.36,173.49,64.24,...,35.72,89.80,64.59,64.47,57.21,130.59,124.94,533.95,62.99,216.20

In [53]:
sector_data = utils.get_snp500()['GICS Sector'][close.columns]

In [54]:
sector_data

ticker
A                  Health Care
AAP     Consumer Discretionary
AAPL    Information Technology
ABBV               Health Care
ABC                Health Care
                 ...
XYL                Industrials
YUM     Consumer Discretionary
ZBRA    Information Technology
ZION                Financials
ZTS                Health Care
Name: GICS Sector, Length: 437, dtype: object

In [55]:
set(sector_data.values)

{'Communication Services',
 'Consumer Discretionary',
 'Consumer Staples',
 'Energy',
 'Financials',
 'Health Care',
 'Industrials',
 'Information Technology',
 'Materials',
 'Real Estate',
 'Utilities'}

In [56]:
sector_helper = {}
for sector in set(sector_data.values):
    sector_tickers = sector_data[lambda x: x==sector].index.to_list()
    sector_helper[sector] = sector_tickers

In [57]:
sector_helper['Industrials']

['ALK',
 'ALLE',
 'AME',
 'AOS',
 'BA',
 'CARR',
 'CAT',
 'CHRW',
 'CMI',
 'CPRT',
 'CSX',
 'CTAS',
 'DOV',
 'EFX',
 'EMR',
 'ETN',
 'EXPD',
 'FAST',
 'FBHS',
 'FDX',
 'FTV',
 'GD',
 'GE',
 'GNRC',
 'GWW',
 'HII',
 'HON',
 'IEX',
 'INFO',
 'ITW',
 'J',
 'JBHT',
 'JCI',
 'KSU',
 'LDOS',
 'LHX',
 'LMT',
 'MMM',
 'NOC',
 'ODFL',
 'OTIS',
 'PCAR',
 'PH',
 'PNR',
 'PWR',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'RSG',
 'RTX',
 'SNA',
 'SWK',
 'TDG',
 'TDY',
 'TT',
 'TXT',
 'UAL',
 'UNP',
 'UPS',
 'URI',
 'VRSK',
 'WAB',
 'XYL']

In [61]:
alpha_factors = alpha_factors.OvernightSentiment(price_histories, 5)

In [62]:
 alpha_factors.factor_data[sector_helper['Industrials']]

ticker,ALK,ALLE,AME,AOS,BA,CARR,CAT,CHRW,CMI,CPRT,...,TDY,TT,TXT,UAL,UNP,UPS,URI,VRSK,WAB,XYL
date,,,,,,,,,,,,,,,,,,,,,
2016-11-01 00:00:00+00:00,0.001680,-0.002206,-0.011584,-0.004472,-0.002879,0.000000,-0.001094,0.000292,-0.004089,-0.003659,...,-0.001707,0.000446,-0.000253,-0.000893,0.002162,0.000749,-0.005751,0.005683,-0.004329,0.008053
2016-11-02 00:00:00+00:00,0.001680,-0.001417,0.003155,-0.002655,-0.002808,0.000000,0.005440,0.003798,-0.003103,-0.004624,...,0.010719,0.002378,0.002824,0.008370,0.002049,0.003742,-0.000252,0.010062,-0.004462,0.011460
2016-11-03 00:00:00+00:00,0.002254,0.001585,0.003155,-0.002198,-0.009307,0.000000,0.006301,0.006554,-0.001706,-0.008274,...,0.010815,0.003124,0.003593,0.009621,0.001260,0.002905,0.000855,0.003024,-0.007247,0.012095
2016-11-04 00:00:00+00:00,0.018195,0.019184,0.017122,0.014297,0.004739,0.000000,0.023675,0.014852,0.020094,0.001767,...,0.030068,0.018106,0.024576,0.022377,0.015231,0.012443,0.031758,0.016478,0.008743,0.027918
2016-11-07 00:00:00+00:00,0.016679,0.017503,0.017791,0.010347,-0.003021,0.000000,0.023913,0.017407,0.015184,-0.002667,...,0.022934,0.015985,0.021140,0.022206,0.015672,0.010713,0.022430,0.014673,0.003558,0.026476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-25 00:00:00+00:00,0.002250,-0.038314,0.003980,0.006905,0.003520,0.000611,-0.014195,0.014758,-0.003592,0.011425,...,0.000428,0.003319,-0.008336,0.012456,0.025904,0.049854,-0.003580,0.011790,0.004008,0.005243
2021-10-26 00:00:00+00:00,0.002863,-0.041321,0.003434,0.000950,0.020232,-0.005324,-0.011239,0.012813,-0.004638,0.008567,...,0.044776,-0.000555,-0.008473,0.004796,0.023511,0.040234,-0.002513,-0.011530,-0.014312,0.003575
2021-10-27 00:00:00+00:00,0.000363,0.011901,0.010271,0.047519,0.015568,-0.000126,0.007717,0.012642,-0.000283,0.007360,...,0.047492,0.004681,0.000638,0.003610,0.021029,0.043582,0.056705,-0.013854,-0.014858,0.004275
2021-10-28 00:00:00+00:00,0.018391,0.003585,0.003556,0.044755,0.009496,-0.024213,0.034246,0.001345,-0.000417,-0.000717,...,0.042984,-0.004963,-0.008573,0.013084,0.005401,0.041017,0.060640,-0.018070,-0.022265,-0.000493
2021-10-29 00:00:00+00:00,0.020435,0.003435,0.002946,0.048499,0.008181,-0.014334,0.031107,0.001345,0.003779,-0.002293,...,0.041056,0.002599,-0.008841,0.017150,0.002412,0.044893,0.059228,-0.017182,-0.022265,0.002070

In [70]:
demeaned_sectors = []
for sector_tickers in sector_helper.values():
    sector_factor_data = alpha_factors.factor_data[sector_tickers]
    demeaned_sectors.append(sector_factor_data.sub(sector_factor_data.mean(axis=1), axis=0))
    
pd.concat(demeaned_sectors, axis=1).describe()

ticker,ADM,CAG,CHD,CL,CLX,COST,CPB,EL,GIS,HRL,...,STX,SWKS,TEL,TER,TRMB,TXN,TYL,V,WU,ZBRA
count,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,...,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000
mean,0.001524,-0.000488,-0.000678,-0.000492,-0.001257,0.002228,-0.002735,0.003903,-0.002119,-0.002001,...,-0.006222,-0.000742,-0.002274,0.001706,-0.001136,-0.003618,-0.003559,-0.000935,-0.004662,0.001464
std,0.012158,0.015246,0.013236,0.012034,0.018833,0.013195,0.017919,0.019238,0.013618,0.013028,...,0.029066,0.023193,0.014506,0.023202,0.015966,0.014998,0.015025,0.010451,0.016091,0.017951
min,-0.062539,-0.070362,-0.118981,-0.055213,-0.110457,-0.051801,-0.128137,-0.094697,-0.091177,-0.088657,...,-0.186985,-0.092661,-0.095672,-0.123942,-0.096700,-0.110272,-0.100756,-0.035120,-0.083958,-0.079336
25%,-0.003847,-0.005815,-0.005431,-0.005426,-0.006942,-0.004263,-0.007491,-0.003882,-0.006005,-0.005719,...,-0.014353,-0.009231,-0.008738,-0.008712,-0.008584,-0.009045,-0.010102,-0.006911,-0.011174,-0.007067
50%,0.002123,-0.000330,0.000515,-0.000340,-0.000943,0.002104,-0.001065,0.002886,-0.000424,-0.000288,...,-0.003605,-0.002120,-0.002351,-0.000150,-0.001715,-0.002800,-0.003226,-0.001524,-0.004646,-0.000146
75%,0.007616,0.004401,0.005440,0.004236,0.004864,0.008658,0.004592,0.009972,0.004164,0.004416,...,0.004770,0.005702,0.004688,0.009147,0.005418,0.003791,0.003366,0.004871,0.001275,0.006963
max,0.050000,0.081958,0.051734,0.065533,0.155647,0.067559,0.065891,0.111055,0.062468,0.046951,...,0.143909,0.215473,0.074201,0.119415,0.073798,0.059328,0.115803,0.057878,0.133575,0.104103

In [72]:
alpha_factors.factor_data.describe()

ticker,A,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,ADM,...,WY,WYNN,XEL,XOM,XRAY,XYL,YUM,ZBRA,ZION,ZTS
count,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,...,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000
mean,0.005034,0.004738,0.002953,0.002869,0.001593,0.002721,0.001401,0.005929,0.003579,0.002100,...,0.001722,0.006590,-0.000432,0.002839,0.000103,0.002543,0.001730,0.007189,0.003622,0.003778
std,0.024390,0.032991,0.026580,0.022445,0.024480,0.021243,0.020713,0.025087,0.024006,0.019203,...,0.025466,0.048249,0.014980,0.025850,0.026756,0.025526,0.021129,0.027410,0.028769,0.019891
min,-0.174476,-0.171004,-0.182154,-0.131249,-0.191590,-0.185389,-0.163568,-0.184438,-0.155574,-0.158127,...,-0.209884,-0.276116,-0.162945,-0.169463,-0.187678,-0.221378,-0.158277,-0.218469,-0.171545,-0.154339
25%,-0.003101,-0.006101,-0.007149,-0.006341,-0.006164,-0.004972,-0.006294,-0.004330,-0.007422,-0.004042,...,-0.005215,-0.012364,-0.005390,-0.008751,-0.007076,-0.004088,-0.003430,-0.002890,-0.009676,-0.004067
50%,0.004878,0.004459,0.003197,0.003136,0.002570,0.002042,0.002627,0.005700,0.004376,0.003275,...,0.002399,0.005939,0.000212,0.002270,0.001933,0.004605,0.002824,0.007063,0.003560,0.004344
75%,0.014148,0.014245,0.014268,0.011619,0.010317,0.009399,0.009669,0.016444,0.015679,0.010436,...,0.010554,0.023197,0.005902,0.012736,0.009729,0.012722,0.009173,0.017070,0.016546,0.011916
max,0.120438,0.188325,0.124859,0.120248,0.159090,0.160525,0.094618,0.117632,0.090700,0.076012,...,0.177563,0.401825,0.067709,0.161669,0.135573,0.115065,0.137347,0.123031,0.160753,0.094521