# Portfolio Workflow

In [1]:
from platform import python_version
import time
from datetime import datetime, timedelta
import os
import pandas as pd
import pandas_datareader as pdr

import numpy as np
import math
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
import pickle

%matplotlib inline
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (20, 8)

# Set the import path for the tools directiory
import sys
# insert at position 1 in the path, as 0 is the path of this file.
sys.path.insert(1, 'tools')
import importlib
import ameritrade_functions as amc
importlib.reload(amc)
import trading_factors as alpha_factors
importlib.reload(alpha_factors)
import utils
importlib.reload(utils)
import nonoverlapping_estimator as ai_estimator
importlib.reload(ai_estimator)

print(f'Python version: {python_version()}')
print(f'Pandas version: {pd.__version__}')
print(f'Pandas Data Reader version: {pdr.__version__}')

Sci-Kit version: 0.24.1
Sci-Kit version: 0.24.1
Python version: 3.8.8
Pandas version: 1.3.5
Pandas Data Reader version: 0.10.0

In [2]:
daily_reader = pdr.yahoo.daily.YahooDailyReader(symbols='AAPL', start='2017-03-27', adjust_price=True, interval='d', get_actions=False, adjust_dividends=True)
ticker_data = daily_reader.read()
daily_reader.close()
ticker_data

,High,Low,Open,Close,Volume,Adj_Ratio
Date,,,,,,
2017-03-27,33.333568,32.719862,32.901614,33.253315,94300400.0,0.94416
2017-03-28,33.999190,33.191934,33.260388,33.942543,133499200.0,0.94416
2017-03-29,34.105407,33.798555,33.914212,34.018070,116760000.0,0.94416
2017-03-30,34.107773,33.871733,34.034601,33.973228,84829200.0,0.94416
2017-03-31,34.053496,33.756083,33.923673,33.909512,78646800.0,0.94416
...,...,...,...,...,...,...
2022-04-04,178.490005,174.440002,174.570007,178.440002,76468400.0,1.00000
2022-04-05,178.300003,174.419998,177.500000,175.059998,73401800.0,1.00000
2022-04-06,173.630005,170.130005,172.360001,171.830002,89058800.0,1.00000
2022-04-07,173.360001,169.850006,171.160004,172.139999,77594700.0,1.00000
2022-04-08,171.779999,169.199997,171.779999,170.089996,76515900.0,1.00000

In [3]:
daily_reader = pdr.yahoo.daily.YahooDailyReader(symbols=['AAPL', 'GOOG'], start='2017-03-27', adjust_price=True, interval='d', get_actions=False, adjust_dividends=True)
ticker_data = daily_reader.read()
daily_reader.close()
ticker_data

Attributes Adj_Ratio            Close                     High               \
Symbols         AAPL GOOG        AAPL         GOOG        AAPL         GOOG
Date
2017-03-27   0.94416  1.0   33.253315   819.510010   33.333568   821.630005
2017-03-28   0.94416  1.0   33.942551   820.919983   33.999198   825.989990
2017-03-29   0.94416  1.0   34.018089   831.409973   34.105427   832.765015
2017-03-30   0.94416  1.0   33.973232   831.500000   34.107777   833.679993
2017-03-31   0.94416  1.0   33.909504   829.559998   34.053488   831.640015
...              ...  ...         ...          ...         ...          ...
2022-04-04   1.00000  1.0  178.440002  2872.850098  178.490005  2880.875000
2022-04-05   1.00000  1.0  175.059998  2821.260010  178.300003  2871.800049
2022-04-06   1.00000  1.0  171.830002  2743.520020  173.630005  2796.969971
2022-04-07   1.00000  1.0  172.139999  2729.300049  173.360001  2754.030029
2022-04-08   1.00000  1.0  170.089996  2680.209961  171.779999  2725.000000

Attributes         Low                     Open                    Volume  \
Symbols           AAPL         GOOG        AAPL         GOOG         AAPL
Date
2017-03-27   32.719862   803.369995   32.901614   806.950012   94300400.0
2017-03-28   33.191942   814.026978   33.260395   820.409973  133499200.0
2017-03-29   33.798574   822.380005   33.914231   825.000000  116760000.0
2017-03-30   33.871737   829.000000   34.034605   833.500000   84829200.0
2017-03-31   33.756076   827.390015   33.923666   828.969971   78646800.0
...                ...          ...         ...          ...          ...
2022-04-04  174.440002  2816.489990  174.570007  2816.489990   76468400.0
2022-04-05  174.419998  2818.870117  177.500000  2867.989990   73401800.0
2022-04-06  170.130005  2728.362061  172.360001  2783.229980   89058800.0
2022-04-07  169.850006  2697.145020  171.160004  2732.360107   77594700.0
2022-04-08  169.199997  2675.050049  171.779999  2725.000000   76515900.0

Attributes
Symbols          GOOG
Date
2017-03-27  1894300.0
2017-03-28  1620500.0
2017-03-29  1786300.0
2017-03-30  1055300.0
2017-03-31  1401900.0
...               ...
2022-04-04   953800.0
2022-04-05   962800.0
2022-04-06  1178700.0
2022-04-07   972400.0
2022-04-08   821000.0

[1270 rows x 12 columns]

In [4]:
from pathlib import Path

# Make sure we have a data directory
Path('./data').mkdir(parents=True, exist_ok=True) 

# Which account are we interested in
masked_account_number = '#---9216'
account_portfolios_file_name = 'data/portfolio_data.csv'
portfolio_file_name = 'data/portfolio_' + masked_account_number[-4:] + '.csv'
price_histories_file_name = 'data/price_histories_yahoo.csv'

# Stage 1: Generate Stock Universe

- Gather stocks from specific criteria (SP500 top 50...)
- Use stock sentiment to select stocks
- Gather price histories

## Stock Universe

Here we setup the univers. This needs some work. The long term goal is to use a pipeline process to help select stock that are in the top 500 or something similare.

For now we will use stocks from the portfolio, but stocks of interest (high news items), a list of well known stocks (this also has been augmented with some stocks that made Ameritrade's top 10 movers for a couple of days. This Ameritrade funciton has not been coded yet, but should be add down the line to automate pulling these tickers.

# Price History data

One you have a set of investments you want to work with, you will need to pull some historical data for them.

We will obtain 5 years of price histories. In the end this will provide us with 2 years of factor data since some of the factors are based on 1 year returns.

In [5]:
snp_500_stocks = utils.get_snp500()
stock_universe = utils.reduce_universe_by_sentiment(set(snp_500_stocks.index.to_list()))

Number of stocks in universe: 505

Tickers:   0%|          | 0/505 [00:00<?, ?Finvis Postings/s]

News Tables:   0%|          | 0/503 [00:00<?, ?News Table Items/s]

Mean Sentiment: 2.1805816031752623 with a standared deviation of: 1.7473050449529406 providing a cutoff of: 0.4332765582223217
New number of stocks in universe: 436
['AAL', 'AAP', 'AAPL', 'ABBV', 'ABC', 'ABMD', 'ABT', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AES', 'AFL', 'AIG', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALK', 'ALL', 'ALLE', 'AMAT', 'AMCR', 'AMGN', 'AMP', 'AMT', 'AMZN', 'ANET', 'ANSS', 'ANTM', 'AON', 'APA', 'APD', 'ARE', 'ATO', 'ATVI', 'AVB', 'AVGO', 'AVY', 'AWK', 'AXP', 'AZO', 'BA', 'BAC', 'BAX', 'BBWI', 'BBY', 'BDX', 'BEN', 'BIIB', 'BIO', 'BK', 'BKNG', 'BLL', 'BMY', 'BR', 'BRO', 'BSX', 'BWA', 'BXP', 'C', 'CAH', 'CARR', 'CAT', 'CB', 'CBOE', 'CBRE', 'CCI', 'CCL', 'CDNS', 'CDW', 'CE', 'CERN', 'CF', 'CHRW', 'CHTR', 'CI', 'CINF', 'CL', 'CLX', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP', 'COF', 'COO', 'COP', 'COST', 'CPRT', 'CPT', 'CRL', 'CRM', 'CSCO', 'CTAS', 'CTLT', 'CTRA', 'CTSH', 'CTVA', 'CTXS', 'CVS', 'CVX', 'CZR', 'D', 'DAL', 'DD', 'DE', 'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIS', 'DISCA', 'DISCK', 'DISH', 'DLR', 'DLTR', 'DOW', 'DPZ', 'DRE', 'DTE', 'DUK', 'DVA', 'DVN', 'DXCM', 'EBAY', 'ECL', 'ED', 'EFX', 'EIX', 'EL', 'EMN', 'EMR', 'ENPH', 'EOG', 'EPAM', 'EQIX', 'ETN', 'ETR', 'ETSY', 'EVRG', 'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'FANG', 'FAST', 'FB', 'FCX', 'FDS', 'FDX', 'FE', 'FFIV', 'FIS', 'FISV', 'FITB', 'FLT', 'FMC', 'FRC', 'FRT', 'FTNT', 'FTV', 'GD', 'GE', 'GILD', 'GIS', 'GNRC', 'GPC', 'GPN', 'GRMN', 'GWW', 'HBAN', 'HCA', 'HD', 'HES', 'HIG', 'HII', 'HLT', 'HOLX', 'HON', 'HPE', 'HPQ', 'HRL', 'HSIC', 'HSY', 'HWM', 'IBM', 'ICE', 'IDXX', 'IEX', 'IFF', 'ILMN', 'INTC', 'INTU', 'IP', 'IPG', 'IQV', 'IRM', 'ISRG', 'IT', 'ITW', 'IVZ', 'J', 'JBHT', 'JCI', 'JKHY', 'JNJ', 'JNPR', 'K', 'KEY', 'KEYS', 'KHC', 'KMB', 'KMI', 'KMX', 'KO', 'KR', 'L', 'LDOS', 'LH', 'LHX', 'LIN', 'LKQ', 'LLY', 'LMT', 'LNC', 'LNT', 'LOW', 'LUMN', 'LUV', 'LVS', 'LYB', 'LYV', 'MA', 'MAA', 'MAR', 'MAS', 'MCD', 'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'MGM', 'MHK', 'MKC', 'MKTX', 'MLM', 'MMC', 'MMM', 'MNST', 'MO', 'MOH', 'MOS', 'MPC', 'MPWR', 'MRK', 'MRO', 'MS', 'MSFT', 'MSI', 'MTB', 'MTCH', 'MTD', 'MU', 'NCLH', 'NDAQ', 'NDSN', 'NEE', 'NEM', 'NFLX', 'NI', 'NKE', 'NLOK', 'NLSN', 'NOC', 'NOW', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NVR', 'NWL', 'NWS', 'NWSA', 'NXPI', 'O', 'ODFL', 'OGN', 'OKE', 'OMC', 'ORCL', 'ORLY', 'OTIS', 'OXY', 'PARA', 'PAYC', 'PAYX', 'PCAR', 'PEG', 'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PKI', 'PLD', 'PM', 'PNC', 'PNR', 'PNW', 'POOL', 'PPG', 'PPL', 'PRU', 'PSA', 'PSX', 'PTC', 'PWR', 'PXD', 'PYPL', 'QCOM', 'QRVO', 'RCL', 'RE', 'REGN', 'RF', 'RHI', 'RJF', 'RL', 'RMD', 'ROK', 'ROL', 'ROP', 'ROST', 'RSG', 'RTX', 'SBAC', 'SBNY', 'SBUX', 'SCHW', 'SEDG', 'SHW', 'SIVB', 'SJM', 'SLB', 'SNA', 'SNPS', 'SO', 'SPG', 'SPGI', 'SRE', 'STT', 'STX', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY', 'T', 'TDG', 'TDY', 'TECH', 'TEL', 'TER', 'TFC', 'TGT', 'TJX', 'TMO', 'TMUS', 'TPR', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TSN', 'TT', 'TTWO', 'TXN', 'TXT', 'TYL', 'UAL', 'UDR', 'ULTA', 'UNH', 'UNP', 'UPS', 'URI', 'USB', 'V', 'VFC', 'VLO', 'VMC', 'VRSK', 'VRSN', 'VTR', 'VZ', 'WAB', 'WAT', 'WBA', 'WDC', 'WEC', 'WELL', 'WFC', 'WHR', 'WMB', 'WMT', 'WRB', 'WRK', 'WST', 'WTW', 'WY', 'XEL', 'XOM', 'XRAY', 'XYL', 'YUM', 'ZBH', 'ZBRA', 'ZION', 'ZTS']

In [13]:
from dateutil.relativedelta import relativedelta
number_of_years = 5
start = datetime.today() - relativedelta(years = number_of_years)
end = datetime.today() - relativedelta(days = 1)
yahoo = pdr.yahoo.daily.YahooDailyReader(symbols=stock_universe, start=start, end=end, adjust_price=True, interval='d', get_actions=False, adjust_dividends=True)
price_histories = yahoo.read()
yahoo.close()
price_histories.to_csv(price_histories_file_name, index=True)

In [11]:
test_read = pd.read_csv(price_histories_file_name, header=[0, 1], index_col=[0], low_memory=False)

In [12]:
test_read

Attributes Adj_Ratio                                                        \
Symbols          AAL       AAP     AAPL      ABBV       ABC ABMD       ABT
Date
2017-04-10  0.968482  0.963511  0.94416  0.794468  0.917661  1.0  0.917953
2017-04-11  0.968482  0.963511  0.94416  0.802373  0.917661  1.0  0.923567
2017-04-12  0.968482  0.963511  0.94416  0.802372  0.917661  1.0  0.923567
2017-04-13  0.968483  0.963510  0.94416  0.802373  0.917661  1.0  0.923568
2017-04-17  0.968482  0.963511  0.94416  0.802373  0.917660  1.0  0.923567
...              ...       ...      ...       ...       ...  ...       ...
2022-04-04  1.000000  1.000000  1.00000  1.000000  1.000000  1.0  1.000000
2022-04-05  1.000000  1.000000  1.00000  1.000000  1.000000  1.0  1.000000
2022-04-06  1.000000  1.000000  1.00000  1.000000  1.000000  1.0  1.000000
2022-04-07  1.000000  1.000000  1.00000  1.000000  1.000000  1.0  1.000000
2022-04-08  1.000000  1.000000  1.00000  1.000000  1.000000  1.0  1.000000

Attributes                           ...     Volume                         \
Symbols          ACN ADBE       ADI  ...         WY        XEL         XOM
Date                                 ...
2017-04-10  0.922028  1.0  0.906076  ...  3854000.0  1655400.0   8885300.0
2017-04-11  0.931594  1.0  0.906076  ...  5591800.0  1965800.0   8576500.0
2017-04-12  0.931594  1.0  0.906076  ...  3235300.0  2450600.0   9516100.0
2017-04-13  0.931594  1.0  0.906076  ...  2780700.0  2345900.0   8667900.0
2017-04-17  0.931594  1.0  0.906076  ...  2882900.0  1791100.0   9577200.0
...              ...  ...       ...  ...        ...        ...         ...
2022-04-04  1.000000  1.0  1.000000  ...  3722900.0  2082300.0  20869400.0
2022-04-05  1.000000  1.0  1.000000  ...  2985100.0  2979400.0  21753100.0
2022-04-06  1.000000  1.0  1.000000  ...  3245900.0  3350600.0  24768200.0
2022-04-07  1.000000  1.0  1.000000  ...  3800800.0  3228700.0  26122000.0
2022-04-08  1.000000  1.0  1.000000  ...  2716200.0  2115100.0  24863600.0

Attributes                                                                   \
Symbols          XRAY        XYL        YUM        ZBH      ZBRA       ZION
Date
2017-04-10   725100.0  1099300.0  2363900.0   471637.0  156300.0  1931900.0
2017-04-11  1112700.0   980700.0  2116000.0   512734.0  211900.0  2931600.0
2017-04-12   936700.0  2104500.0  1485000.0   677225.0  314100.0  3286600.0
2017-04-13   917000.0  1039800.0  1965900.0   709052.0  323600.0  2627800.0
2017-04-17   579500.0   790100.0  1617000.0   572371.0  236000.0  2241300.0
...               ...        ...        ...        ...       ...        ...
2022-04-04  1036400.0   850700.0  1980400.0  1349700.0  492300.0  1220400.0
2022-04-05  1410600.0  1346100.0  2010900.0  2187100.0  456700.0  1384200.0
2022-04-06  1706000.0  1271300.0  1683100.0  2057700.0  442300.0  1568200.0
2022-04-07  1240400.0  1153100.0  2008900.0  1800200.0  464500.0  1093500.0
2022-04-08  1252100.0  1363500.0  1743200.0  1107600.0  387600.0   889300.0

Attributes
Symbols           ZTS
Date
2017-04-10  1772300.0
2017-04-11  1976400.0
2017-04-12  2764500.0
2017-04-13  2104900.0
2017-04-17  1975300.0
...               ...
2022-04-04  2603600.0
2022-04-05  2059300.0
2022-04-06  2843500.0
2022-04-07  2781400.0
2022-04-08  2455500.0

[1260 rows x 2616 columns]